import Head from "next/head";
import styled from "styled-components";

const ComingSoonHeading = styled.h1`
    text-align: center;
    margin: 80px 0;
`;

export default function Home() {
    return (
        <div>
            <Head>
                <title>Grimoire - Modular MUD Web Client</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ComingSoonHeading>Landing Page</ComingSoonHeading>
        </div>
    );
}
